services:
  app:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - DB_USER=user
      - DB_PASSWORD=pwpw
      - DB_NAME=jeycc_db
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: jeycc_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwpw
      POSTGRES_DB: jeycc_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: